import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import ReduxProvider from "@/ReduxProvider/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Amazon Clone",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {

   return (
      <html lang="en">
         <ReduxProvider>
            <body className={"main"}>
               
               {children}
            </body>
         </ReduxProvider>
      </html>
   );
}
